{
 "title": "Dag Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Dag Failures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(airflow_task_failures_total[5m])) by (dag_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAG Runs success rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(airflow_dagrun_duration_success{dag_id!=\"\"})\r\n/\r\nsum(airflow_dagrun_duration{dag_id!=\"\"})\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "avg(airflow_task_duration{dag_id!=\"\"}) by (dag_id)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}