{
 "title": "Infrastructure k8s",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Kube", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory_Usage_Namespace_Kube-System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",namespace=~\"kube-system\"}) by (namespace) / sum(kube_pod_container_resource_limits{id!=\"/\",namespace=~\"kube-system\",resource=\"memory\"}) by (namespace)* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu_Usage_Namespace_Kube-System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",namespace=~\"kube-system\"}[5m])) by (pod)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory_Usage_Namespace_Monitoring",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{id!=\"/\",namespace=~\"monitoring\"}) by (namespace) / sum(kube_pod_container_resource_limits{id!=\"/\", namespace=~\"monitoring\", resource=\"memory\"}) by (namespace)* 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cpu_Usage_Namespace_Monitoring",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",namespace=~\"monitoring\"}[5m])) by (pod)*100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Airflow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory_Usage_Namespace_Airflow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id!=\"/\",namespace=~\"airflow\"}) by (namespace) / sum(kube_pod_container_resource_limits{id!=\"/\", namespace=~\"airflow\", resource=\"memory\"}) by (namespace)* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu_Usage_Namespace_Airflow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",namespace=~\"airflow\"}[5m])) by (pod)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Datalake",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory_Usage_Namespace_Datalake",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{id!=\"/\",namespace=~\"datalake\"}) by (namespace) / sum(kube_pod_container_resource_limits{id!=\"/\", namespace=~\"datalake\", resource=\"memory\"}) by (namespace)* 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cpu_Usage_Namespace_Datalake",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",namespace=~\"datalake\"}[5m])) by (pod)*100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Traefik",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory_Usage_Namespace_Traefik",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{id!=\"/\",namespace=~\"traefik\"}) by (namespace) / sum(kube_pod_container_resource_limits{id!=\"/\", namespace=~\"traefik\", resource=\"memory\"}) by (namespace)* 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cpu_Usage_Namespace_Traefik",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",namespace=~\"traefik\"}[5m])) by (pod)*100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory_Usage_Namespace_Documentation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{id!=\"/\",namespace=~\"documentation\"}) by (namespace) / sum(kube_pod_container_resource_limits{id!=\"/\", namespace=~\"documentation\", resource=\"memory\"}) by (namespace)* 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cpu_Usage_Namespace_Documentation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",namespace=~\"documentation\"}[5m])) by (pod)*100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}